# Generated by Django 4.1.13 on 2024-07-13 10:04

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('influencer', '0007_influencer_last_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='influencer',
            options={'verbose_name': 'Influencer', 'verbose_name_plural': 'Influencers'},
        ),
        migrations.AddField(
            model_name='influencer',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='influencer_groups', related_query_name='influencer_group', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='influencer_user_permissions', related_query_name='influencer_user_permission', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
